---
title: "Fold Change with Abundance plot"
author: "Katherine Heal"
date: "November 6, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
library("vegan")
library("pastecs")
library("simba")
library("ecodist")
library("MASS")
library("caret")
library("e1071")
library("cowplot")
library(plotly)
library(tidyverse)
library(dplyr)
library(ggplot2) 
library(gridExtra) 
library(dplyr) 
library(seqinr) 
library(lubridate)
library(reshape2)
library(tidyr)
library(Hmisc)
library(gtools)
library(cowplot)
require(RColorBrewer)
library(readr)
library(plotly)
library(stringr)
library(devtools)
library(RCurl)


source('~/Google_Drive/6_Classes/1_FISH560/R_SourceCode/coldiss.R', encoding = 'UTF-8' )
source('~/Google_Drive/6_Classes/1_FISH560/R_SourceCode/biostats.R', encoding = 'UTF-8' )
setwd("~/Google_Drive/0_Manuscripts/_B12_Demand_Cultures_paper/_Working_manuscript/2_Figures_Working/F3_OverallResultsFigureTQS")
```


#Get wide data with stats
```{r, warning=FALSE, error=FALSE, message=FALSE}
setwd("~/Google_Drive/0_Manuscripts/_B12_Demand_Cultures_paper/1_Targeted_DataAnalysis/TP")
TPTQSdatAll <- read_csv("Combined/Filtered_Wide_Combined_wStats.csv",comment = "#")
TPTQSdat <- TPTQSdatAll %>% 
  select(Compound.Name:RB12LL_EF) 


setwd("~/Google_Drive/0_Manuscripts/_B12_Demand_Cultures_paper/1_Targeted_DataAnalysis/NP")
NPTQSdatAll <- read_csv("Combined/Filtered_Wide_Combined_wStats.csv",comment = "#")
NPTQSdat <- NPTQSdatAll %>% 
    select(Compound.Name:RB12LL_EF) 

```


#Make new column that is a combo of BOTH, ONE, or NONE
```{r, warning=FALSE, error=FALSE, message=FALSE}
TPSigs <-TPTQSdatAll %>%
  select(Compound.Name, B12Sig, B12HLSig, B12LLSig, LightSig, LightRB12Sig, LightLB12Sig)
Both <- TPSigs %>%
  filter(B12Sig == "TRUE" | (B12HLSig == "TRUE" & B12LLSig == "TRUE")) %>%
  mutate(B12SigToPlot = "BOTH")
One <- TPSigs %>%
  filter(B12HLSig == "TRUE" | B12LLSig == "TRUE") %>%
  filter(!Compound.Name %in% Both$Compound.Name) %>%
  mutate(B12SigToPlot = "ONE")
Neither <- TPSigs %>%
  filter(!Compound.Name %in% Both$Compound.Name) %>%
  filter(!Compound.Name %in% One$Compound.Name) %>%
  mutate(B12SigToPlot = "NONE")
B12SigToPlot <- rbind(Neither, One, Both)
Both <- TPSigs %>%
  filter(LightSig == "TRUE" | (LightRB12Sig == "TRUE" & LightLB12Sig == "TRUE")) %>%
  mutate(LightSigToPlot = "BOTH")
One <- TPSigs %>%
  filter(LightRB12Sig == "TRUE" | LightLB12Sig == "TRUE") %>%
  filter(!Compound.Name %in% Both$Compound.Name) %>%
  mutate(LightSigToPlot = "ONE")
Neither <- TPSigs %>%
  filter(!Compound.Name %in% Both$Compound.Name) %>%
  filter(!Compound.Name %in% One$Compound.Name) %>%
  mutate(LightSigToPlot = "NONE")
LightSigToPlot <- rbind(Neither, One, Both)
TPTQSdatAll <- TPTQSdatAll %>% left_join(B12SigToPlot) %>% left_join(LightSigToPlot)

##FOR NP WHEN NP STATS HAVE BEEN RUN.
# NPSigs <-NPTQSdatAll %>%
#   select(Compound.Name, B12Sig, B12HLSig, B12LLSig, LightSig, LightRB12Sig, LightLB12Sig)
# Both <- TPSigs %>%
#   filter(B12Sig == "TRUE" | (B12HLSig == "TRUE" & B12LLSig == "TRUE")) %>%
#   mutate(B12SigToPlot = "BOTH")
# One <- TPSigs %>%
#   filter(B12HLSig == "TRUE" | B12LLSig == "TRUE") %>%
#   filter(!Compound.Name %in% Both$Compound.Name) %>%
#   mutate(B12SigToPlot = "ONE")
# Neither <- TPSigs %>%
#   filter(!Compound.Name %in% Both$Compound.Name) %>%
#   filter(!Compound.Name %in% One$Compound.Name) %>%
#   mutate(B12SigToPlot = "NONE")
# B12SigToPlot <- rbind(Neither, One, Both)
# NPTQSdatAll <- NPTQSdatAll %>% left_join(B12SigToPlot)
NPSigs <-NPTQSdatAll %>%
  select(Compound.Name, B12Sig, B12HLSig, B12LLSig, LightSig, LightRB12Sig, LightLB12Sig)
Both <- NPSigs %>%
  mutate(B12SigToPlot = "BOTH") %>%
  filter(B12Sig == "TRUE" | (B12HLSig == "TRUE" & B12LLSig == "TRUE")) 
One <- NPSigs %>%
  mutate(B12SigToPlot = "ONE")%>%
  filter(B12HLSig == "TRUE" | B12LLSig == "TRUE") %>%
  filter(!Compound.Name %in% Both$Compound.Name) 
Neither <- NPSigs %>%
  filter(!Compound.Name %in% Both$Compound.Name) %>%
  filter(!Compound.Name %in% One$Compound.Name) %>%
  mutate(B12SigToPlot = "NONE")
B12SigToPlot <- rbind(Neither, One, Both)
Both <- NPSigs %>%
  filter(LightSig == "TRUE" | (LightRB12Sig == "TRUE" & LightLB12Sig == "TRUE")) %>%
  mutate(LightSigToPlot = "BOTH")
One <- NPSigs %>%
  filter(LightRB12Sig == "TRUE" | LightLB12Sig == "TRUE") %>%
  filter(!Compound.Name %in% Both$Compound.Name) %>%
  mutate(LightSigToPlot = "ONE")
Neither <- NPSigs %>%
  filter(!Compound.Name %in% Both$Compound.Name) %>%
  filter(!Compound.Name %in% One$Compound.Name) %>%
  mutate(LightSigToPlot = "NONE")
LightSigToPlot <- rbind(Neither, One, Both)
NPTQSdatAll <- NPTQSdatAll %>% left_join(B12SigToPlot) %>% left_join(LightSigToPlot)
```

#Tp Plot - B12
```{r Univariate stats for overall changes}
a <- ggplot(TPTQSdatAll, aes(x = AveSmp, y = -1*(RvLB12_FC), fill = B12SigToPlot, alpha = B12SigToPlot,
                            text = Compound.Name))+
  geom_point(size = 3, shape = 21, stroke=0)+  
  scale_fill_manual(values =c("royalblue4", "grey", "lightskyblue3")) +
  scale_alpha_manual(values =c(1, 0.5, 0.7))+
  scale_x_log10() +
  ggtitle("Thalassiosira pseudonana") +
  theme(plot.title = element_text(face= "italic", size = 9),
        legend.position="none",
        axis.title.x=element_text(size=8),
        axis.title.y=element_text(size=8),
        axis.text=element_text(size=8))+
  labs(x="Average peak size", y=expression(paste(Log[2], "(Limited/Replete Cobalamin)", sep = ""))) +
  theme(legend.position="none")+
  scale_y_continuous(limits=c(-6, 6))
a
#ggplotly()

```

#Tp Plot - Light
```{r Univariate stats for overall changes}
b <- ggplot(TPTQSdatAll, aes(x = AveSmp, y = -1*(HvsLL_FC), fill = LightSigToPlot, alpha = LightSigToPlot, 
                             text = Compound.Name))+
  geom_point(size = 3, shape = 21, stroke=0)+  
  scale_fill_manual(values =c("royalblue4", "grey", "lightskyblue3")) +
  scale_alpha_manual(values =c(1, 0.5, 0.7))+
  scale_x_log10()  +
  theme(plot.title = element_text(face= "italic"),
        legend.position="none",
        axis.title.y=element_text(size=9),
        axis.title.x=element_text(size=9),
        axis.text=element_text(size=9))+
  labs(x="Average peak size") +
  labs(x="Average peak size",y=expression(paste(Log[2], "(Low/High light)", sep = "")))+
         theme(legend.position="none") +
  scale_y_continuous(limits=c(-6, 6))
#b
#b
#ggplotly()
```

#Np Plot - B12
```{r Univariate stats for overall changes}
c <- ggplot(NPTQSdatAll,  aes(x = AveSmp, y = -1*(RvLB12_FC), fill = B12SigToPlot, alpha = B12SigToPlot, 
                             text = Compound.Name))+
  geom_point(size = 3, shape = 21, stroke=0)+  
  scale_fill_manual(values =c("grey")) +
  scale_alpha_manual(values =c(0.5))+
  scale_x_log10()  +
  ggtitle("Navicula pelliculosa") +
  theme(plot.title = element_text(face= "italic", size = 9),
        legend.position="none",
        axis.title.x=element_text(size=8),
        axis.title.y=element_blank(),
        axis.text=element_text(size=8))+
  labs(x="Average peak size") +
   theme(legend.position="none")+
  scale_y_continuous(limits=c(-6, 6))
#c
#ggplotly()
```

#Np Plot - Light
```{r Univariate stats for overall changes}
d <- ggplot(NPTQSdatAll,  aes(x = AveSmp, y = -1*(HvsLL_FC), 
                              fill = LightSigToPlot, 
                              alpha = LightSigToPlot, text = Compound.Name))+
  geom_point(size = 3, shape = 21, stroke=0)+  
  scale_fill_manual(values =c("royalblue4", "grey", "lightskyblue3")) +
  scale_alpha_manual(values =c(1, 0.5, 0.7))+
  scale_x_log10()  +
  theme(plot.title = element_text(face= "italic"),
        legend.position="none",
        axis.title.y=element_blank(),
        axis.title.x=element_text(size=9),
        axis.text=element_text(size=9))+
  labs(x="Average peak size") +
  theme(legend.position="none")
#d
#ggplotly()
```

#Combine all four plots
```{r}
e <- plot_grid(a, c, labels = "AUTO", ncol = 2, align = 'v')

e

#ggsave doesnt work, but use width = 7.4, height = 4,
#ggsave(e, filename = "/Users/katherineheal/Google_Drive/0_Manuscripts/_B12_Demand_Cultures_paper/_Working_manuscript/2_Figures_Working/F3_OverallResultsFigureTQS/OverallResultsFigure_4Panels.pdf", width = 7.4, height = 4, device = pdf)
```

